// ===== TRANSLATIONS (7 языков) =====
const translations = {
  ru: {
    nav_home: "Главная",
    nav_apps: "Приложения",
    nav_feedback: "Отзывы",
    nav_support: "Поддержка",
    nav_about: "О проекте",
    hero_title: "Aurionyx",
    hero_sub: "Создаём красивые Android-приложения с душой.",
    btn_apps: "📱 Приложения",
    btn_feedback: "💬 Отзывы",
    btn_download: "Скачать",
    btn_soon: "В разработке",
    badge_soon: "Скоро",
    apps_title: "Приложения",
    apps_sub: "Наши проекты для Android",
    app_laplayer: "Музыкальный плеер с виниловой анимацией, 20-полосным эквалайзером и 11 темами.",
    app_laiscanner: "Сканер документов с AI-апскейлом и распознаванием текста.",
    app_laipdf: "PDF-ридер с AI-помощником и 3D-перелистыванием страниц.",
    app_ladevice: "Игра-тайкун: создавай собственные устройства и строй империю.",
    feedback_title: "Отзывы",
    feedback_sub: "Поделитесь мнением о наших приложениях",
    ph_name: "Ваше имя",
    ph_text: "Ваш отзыв или предложение...",
    btn_send: "Отправить",
    support_title: "Поддержка",
    support_sub: "Мы всегда рады помочь",
    contact_title: "Свяжитесь с нами",
    contact_text: "По любым вопросам пишите на email:",
    faq_title: "Частые вопросы",
    faq1_q: "Как связаться с разработчиком?",
    faq1_a: "Пишите на email: cooolget06@gmail.com — ответим в течение 24 часов.",
    faq2_q: "Где скачать приложения?",
    faq2_a: "APK-файлы доступны в разделе \"Приложения\". Нажмите \"Скачать\" рядом с приложением.",
    faq3_q: "Приложения бесплатные?",
    faq3_a: "Да, все приложения Aurionyx полностью бесплатны, без рекламы и подписок.",
    faq4_q: "Будут ли обновления?",
    faq4_a: "Да, мы регулярно выпускаем обновления с новыми функциями и исправлениями.",
    faq5_q: "На каких языках доступны приложения?",
    faq5_a: "Русский, английский, украинский, белорусский, польский, казахский, болгарский.",
    about_title: "О проекте",
    about_sub: "Кто мы и что делаем",
    about_text1: "Aurionyx — независимая студия разработки Android-приложений. Мы создаём красивые, быстрые и бесплатные приложения с уникальным дизайном \"жидкое стекло\".",
    about_text2: "Наша цель — сделать технологии доступными для всех. Без рекламы, без подписок, без слежки.",
    about_dev_title: "Разработчик",
    about_dev_text: "Все приложения созданы Aurionyx при поддержке AI-инструментов.",
    about_contact: "Связаться",
    footer_rights: "Все права защищены.",
    footer_made: "Сделано с 💚 Aurionyx",
    loading: "Загрузка...",
    no_reviews: "Пока нет отзывов. Будьте первым! 💚",
    thanks_feedback: "Спасибо за отзыв! 💚",
    error_feedback: "Напишите отзыв!"
  },
  en: {
    nav_home: "Home",
    nav_apps: "Apps",
    nav_feedback: "Feedback",
    nav_support: "Support",
    nav_about: "About",
    hero_title: "Aurionyx",
    hero_sub: "Crafting beautiful Android apps with soul.",
    btn_apps: "📱 Apps",
    btn_feedback: "💬 Feedback",
    btn_download: "Download",
    btn_soon: "Coming soon",
    badge_soon: "Soon",
    apps_title: "Apps",
    apps_sub: "Our Android projects",
    app_laplayer: "Music player with vinyl animation, 20-band equalizer, and 11 themes.",
    app_laiscanner: "Document scanner with AI upscale and text recognition.",
    app_laipdf: "PDF reader with AI assistant and 3D page flip.",
    app_ladevice: "Tycoon game: build your own devices and empire.",
    feedback_title: "Feedback",
    feedback_sub: "Share your thoughts about our apps",
    ph_name: "Your name",
    ph_text: "Your feedback or suggestion...",
    btn_send: "Send",
    support_title: "Support",
    support_sub: "We're always here to help",
    contact_title: "Contact us",
    contact_text: "For any questions, email us at:",
    faq_title: "FAQ",
    faq1_q: "How to contact the developer?",
    faq1_a: "Email: cooolget06@gmail.com — we reply within 24 hours.",
    faq2_q: "Where to download apps?",
    faq2_a: "APK files are in the \"Apps\" section. Click \"Download\" next to an app.",
    faq3_q: "Are the apps free?",
    faq3_a: "Yes, all Aurionyx apps are completely free, no ads, no subscriptions.",
    faq4_q: "Will there be updates?",
    faq4_a: "Yes, we regularly release updates with new features and fixes.",
    faq5_q: "What languages are supported?",
    faq5_a: "Russian, English, Ukrainian, Belarusian, Polish, Kazakh, Bulgarian.",
    about_title: "About",
    about_sub: "Who we are and what we do",
    about_text1: "Aurionyx is an independent Android app studio. We craft beautiful, fast, and free apps with a unique \"liquid glass\" design.",
    about_text2: "Our goal is to make technology accessible to everyone. No ads, no subscriptions, no tracking.",
    about_dev_title: "Developer",
    about_dev_text: "All apps are created by Aurionyx with AI tooling support.",
    about_contact: "Contact",
    footer_rights: "All rights reserved.",
    footer_made: "Made with 💚 Aurionyx",
    loading: "Loading...",
    no_reviews: "No reviews yet. Be the first! 💚",
    thanks_feedback: "Thanks for your feedback! 💚",
    error_feedback: "Please write a review!"
  },
  uk: {
    nav_home: "Головна",
    nav_apps: "Додатки",
    nav_feedback: "Відгуки",
    nav_support: "Підтримка",
    nav_about: "Про проєкт",
    hero_title: "Aurionyx",
    hero_sub: "Створюємо красиві Android-додатки з душею.",
    btn_apps: "📱 Додатки",
    btn_feedback: "💬 Відгуки",
    btn_download: "Завантажити",
    btn_soon: "У розробці",
    badge_soon: "Скоро",
    apps_title: "Додатки",
    apps_sub: "Наші проєкти для Android",
    app_laplayer: "Музичний плеєр з вініловою анімацією, 20-смуговим еквалайзером та 11 темами.",
    app_laiscanner: "Сканер документів з AI-апскейлом і розпізнаванням тексту.",
    app_laipdf: "PDF-рідер з AI-помічником і 3D-перегортанням сторінок.",
    app_ladevice: "Гра-тайкун: створюй власні пристрої та імперію.",
    feedback_title: "Відгуки",
    feedback_sub: "Поділіться думкою про наші додатки",
    ph_name: "Ваше ім'я",
    ph_text: "Ваш відгук або пропозиція...",
    btn_send: "Надіслати",
    support_title: "Підтримка",
    support_sub: "Ми завжди раді допомогти",
    contact_title: "Зв'яжіться з нами",
    contact_text: "З будь-яких питань пишіть на email:",
    faq_title: "Часті питання",
    faq1_q: "Як зв'язатися з розробником?",
    faq1_a: "Email: cooolget06@gmail.com — відповідаємо протягом 24 годин.",
    faq2_q: "Де завантажити додатки?",
    faq2_a: "APK-файли в розділі \"Додатки\". Натисніть \"Завантажити\".",
    faq3_q: "Додатки безкоштовні?",
    faq3_a: "Так, всі додатки Aurionyx повністю безкоштовні, без реклами.",
    faq4_q: "Чи будуть оновлення?",
    faq4_a: "Так, ми регулярно випускаємо оновлення.",
    faq5_q: "Які мови підтримуються?",
    faq5_a: "Російська, англійська, українська, білоруська, польська, казахська, болгарська.",
    about_title: "Про проєкт",
    about_sub: "Хто ми і що робимо",
    about_text1: "Aurionyx — незалежна студія Android-додатків. Ми створюємо красиві, швидкі та безкоштовні додатки з дизайном \"рідке скло\".",
    about_text2: "Наша мета — зробити технології доступними для всіх.",
    about_dev_title: "Розробник",
    about_dev_text: "Усі додатки створені Aurionyx за підтримки AI-інструментів.",
    about_contact: "Зв'язатися",
    footer_rights: "Всі права захищені.",
    footer_made: "Зроблено з 💚 Aurionyx",
    loading: "Завантаження...",
    no_reviews: "Поки немає відгуків. Будьте першим! 💚",
    thanks_feedback: "Дякуємо за відгук! 💚",
    error_feedback: "Напишіть відгук!"
  },
  be: {
    nav_home: "Галоўная",
    nav_apps: "Дадаткі",
    nav_feedback: "Водгукі",
    nav_support: "Падтрымка",
    nav_about: "Пра праект",
    hero_title: "Aurionyx",
    hero_sub: "Ствараем прыгожыя Android-дадаткі з душой.",
    btn_apps: "📱 Дадаткі",
    btn_feedback: "💬 Водгукі",
    btn_download: "Спампаваць",
    btn_soon: "У распрацоўцы",
    badge_soon: "Хутка",
    apps_title: "Дадаткі",
    apps_sub: "Нашы праекты для Android",
    app_laplayer: "Музычны плэер з вінілавай анімацыяй, 20-палосным эквалайзерам і 11 тэмамі.",
    app_laiscanner: "Сканер дакументаў з AI-апскейлам і распазнаваннем тэксту.",
    app_laipdf: "PDF-рыдэр з AI-памочнікам і 3D-перагортваннем старонак.",
    app_ladevice: "Гульня-тайкун: стварай уласныя прылады і імперыю.",
    feedback_title: "Водгукі",
    feedback_sub: "Падзяліцеся думкай пра нашы дадаткі",
    ph_name: "Ваша імя",
    ph_text: "Ваш водгук або прапанова...",
    btn_send: "Адправіць",
    support_title: "Падтрымка",
    support_sub: "Мы заўсёды рады дапамагчы",
    contact_title: "Звяжыцеся з намі",
    contact_text: "Па любых пытаннях пішыце на email:",
    faq_title: "Частыя пытанні",
    faq1_q: "Як звязацца з распрацоўшчыкам?",
    faq1_a: "Email: cooolget06@gmail.com — адкажам на працягу 24 гадзін.",
    faq2_q: "Дзе спампаваць дадаткі?",
    faq2_a: "APK-файлы ў раздзеле \"Дадаткі\".",
    faq3_q: "Дадаткі бясплатныя?",
    faq3_a: "Так, усе дадаткі Aurionyx цалкам бясплатныя, без рэкламы.",
    faq4_q: "Ці будуць абнаўленні?",
    faq4_a: "Так, мы рэгулярна выпускаем абнаўленні.",
    faq5_q: "Якія мовы падтрымліваюцца?",
    faq5_a: "Руская, англійская, украінская, беларуская, польская, казахская, балгарская.",
    about_title: "Пра праект",
    about_sub: "Хто мы і што робім",
    about_text1: "Aurionyx — незалежная студыя Android-дадаткаў.",
    about_text2: "Наша мэта — зрабіць тэхналогіі даступнымі для ўсіх.",
    about_dev_title: "Распрацоўшчык",
    about_dev_text: "Усе дадаткі створаны Aurionyx.",
    about_contact: "Звязацца",
    footer_rights: "Усе правы абаронены.",
    footer_made: "Зроблена з 💚 Aurionyx",
    loading: "Загрузка...",
    no_reviews: "Пакуль няма водгукаў. Будзьце першым! 💚",
    thanks_feedback: "Дзякуй за водгук! 💚",
    error_feedback: "Напішыце водгук!"
  },
  pl: {
    nav_home: "Główna",
    nav_apps: "Aplikacje",
    nav_feedback: "Opinie",
    nav_support: "Wsparcie",
    nav_about: "O projekcie",
    hero_title: "Aurionyx",
    hero_sub: "Tworzymy piękne aplikacje Android z duszą.",
    btn_apps: "📱 Aplikacje",
    btn_feedback: "💬 Opinie",
    btn_download: "Pobierz",
    btn_soon: "W budowie",
    badge_soon: "Wkrótce",
    apps_title: "Aplikacje",
    apps_sub: "Nasze projekty na Androida",
    app_laplayer: "Odtwarzacz muzyczny z animacją winylu, 20-pasmowym korektorem i 11 motywami.",
    app_laiscanner: "Skaner dokumentów z AI upscale i rozpoznawaniem tekstu.",
    app_laipdf: "Czytnik PDF z asystentem AI i przewracaniem stron 3D.",
    app_ladevice: "Gra tycoon: twórz własne urządzenia i imperium.",
    feedback_title: "Opinie",
    feedback_sub: "Podziel się opinią o naszych aplikacjach",
    ph_name: "Twoje imię",
    ph_text: "Twoja opinia lub sugestia...",
    btn_send: "Wyślij",
    support_title: "Wsparcie",
    support_sub: "Zawsze chętnie pomożemy",
    contact_title: "Skontaktuj się z nami",
    contact_text: "W razie pytań pisz na email:",
    faq_title: "Częste pytania",
    faq1_q: "Jak skontaktować się z deweloperem?",
    faq1_a: "Email: cooolget06@gmail.com — odpowiadamy w 24 godziny.",
    faq2_q: "Gdzie pobrać aplikacje?",
    faq2_a: "Pliki APK są w sekcji \"Aplikacje\".",
    faq3_q: "Czy aplikacje są darmowe?",
    faq3_a: "Tak, wszystkie aplikacje Aurionyx są całkowicie darmowe, bez reklam.",
    faq4_q: "Czy będą aktualizacje?",
    faq4_a: "Tak, regularnie wydajemy aktualizacje.",
    faq5_q: "Jakie języki są obsługiwane?",
    faq5_a: "Rosyjski, angielski, ukraiński, białoruski, polski, kazachski, bułgarski.",
    about_title: "O projekcie",
    about_sub: "Kim jesteśmy i co robimy",
    about_text1: "Aurionyx to niezależne studio aplikacji Android.",
    about_text2: "Naszym celem jest uczynienie technologii dostępnymi dla wszystkich.",
    about_dev_title: "Deweloper",
    about_dev_text: "Wszystkie aplikacje tworzy Aurionyx.",
    about_contact: "Kontakt",
    footer_rights: "Wszelkie prawa zastrzeżone.",
    footer_made: "Stworzone z 💚 Aurionyx",
    loading: "Ładowanie...",
    no_reviews: "Brak opinii. Bądź pierwszy! 💚",
    thanks_feedback: "Dziękujemy za opinię! 💚",
    error_feedback: "Napisz opinię!"
  },
  kk: {
    nav_home: "Басты",
    nav_apps: "Қосымшалар",
    nav_feedback: "Пікірлер",
    nav_support: "Қолдау",
    nav_about: "Жоба туралы",
    hero_title: "Aurionyx",
    hero_sub: "Жанды Android қосымшаларын жасаймыз.",
    btn_apps: "📱 Қосымшалар",
    btn_feedback: "💬 Пікірлер",
    btn_download: "Жүктеу",
    btn_soon: "Әзірленуде",
    badge_soon: "Жақында",
    apps_title: "Қосымшалар",
    apps_sub: "Android жобаларымыз",
    app_laplayer: "Винил анимациясы, 20 жолақты эквалайзер және 11 тақырыппен музыка ойнатқыш.",
    app_laiscanner: "AI upscale және мәтінді танумен құжат сканері.",
    app_laipdf: "AI көмекшісі және 3D бет бұрумен PDF оқырман.",
    app_ladevice: "Тайкун ойыны: өз құрылғыларыңызды және империяңызды жасаңыз.",
    feedback_title: "Пікірлер",
    feedback_sub: "Қосымшаларымыз туралы пікір білдіріңіз",
    ph_name: "Сіздің атыңыз",
    ph_text: "Сіздің пікіріңіз немесе ұсынысыңыз...",
    btn_send: "Жіберу",
    support_title: "Қолдау",
    support_sub: "Біз әрқашан көмектесуге дайынбыз",
    contact_title: "Бізбен байланысыңыз",
    contact_text: "Кез келген сұрақтар бойынша email-ға жазыңыз:",
    faq_title: "Жиі қойылатын сұрақтар",
    faq1_q: "Әзірлеушімен қалай байланысуға болады?",
    faq1_a: "Email: cooolget06@gmail.com — 24 сағат ішінде жауап береміз.",
    faq2_q: "Қосымшаларды қайдан жүктеуге болады?",
    faq2_a: "APK файлдары \"Қосымшалар\" бөлімінде.",
    faq3_q: "Қосымшалар тегін бе?",
    faq3_a: "Иә, барлық Aurionyx қосымшалары толығымен тегін, жарнамасыз.",
    faq4_q: "Жаңартулар бола ма?",
    faq4_a: "Иә, біз үнемі жаңартулар шығарамыз.",
    faq5_q: "Қандай тілдер қолданылады?",
    faq5_a: "Орыс, ағылшын, украин, беларусь, поляк, қазақ, болгар.",
    about_title: "Жоба туралы",
    about_sub: "Біз кімбыз және не істейміз",
    about_text1: "Aurionyx — тәуелсіз Android қосымшалар студиясы.",
    about_text2: "Біздің мақсатымыз — технологияларды барлығына қолжетімді ету.",
    about_dev_title: "Әзірлеуші",
    about_dev_text: "Барлық қосымшаларды Aurionyx жасайды.",
    about_contact: "Байланыс",
    footer_rights: "Барлық құқықтар қорғалған.",
    footer_made: "💚 Aurionyx жасаған",
    loading: "Жүктелуде...",
    no_reviews: "Пікірлер жоқ. Бірінші болыңыз! 💚",
    thanks_feedback: "Пікіріңіз үшін рахмет! 💚",
    error_feedback: "Пікір жазыңыз!"
  },
  bg: {
    nav_home: "Начало",
    nav_apps: "Приложения",
    nav_feedback: "Отзиви",
    nav_support: "Поддръжка",
    nav_about: "За проекта",
    hero_title: "Aurionyx",
    hero_sub: "Създаваме красиви Android приложения с душа.",
    btn_apps: "📱 Приложения",
    btn_feedback: "💬 Отзиви",
    btn_download: "Изтегли",
    btn_soon: "В разработка",
    badge_soon: "Скоро",
    apps_title: "Приложения",
    apps_sub: "Нашите Android проекти",
    app_laplayer: "Музикален плейър с винил анимация, 20-лентов еквалайзер и 11 теми.",
    app_laiscanner: "Скенер за документи с AI upscale и разпознаване на текст.",
    app_laipdf: "PDF четец с AI асистент и 3D прелистване на страници.",
    app_ladevice: "Игра тайкун: създай свои устройства и империя.",
    feedback_title: "Отзиви",
    feedback_sub: "Споделете мнение за нашите приложения",
    ph_name: "Вашето име",
    ph_text: "Вашият отзив или предложение...",
    btn_send: "Изпрати",
    support_title: "Поддръжка",
    support_sub: "Винаги сме готови да помогнем",
    contact_title: "Свържете се с нас",
    contact_text: "За всякакви въпроси пишете на email:",
    faq_title: "Често задавани въпроси",
    faq1_q: "Как да се свържа с разработчика?",
    faq1_a: "Email: cooolget06@gmail.com — отговаряме до 24 часа.",
    faq2_q: "Откъде да изтегля приложенията?",
    faq2_a: "APK файловете са в раздел \"Приложения\".",
    faq3_q: "Приложенията безплатни ли са?",
    faq3_a: "Да, всички приложения на Aurionyx са напълно безплатни, без реклами.",
    faq4_q: "Ще има ли актуализации?",
    faq4_a: "Да, редовно пускаме актуализации.",
    faq5_q: "Какви езици се поддържат?",
    faq5_a: "Руски, английски, украински, беларуски, полски, казахски, български.",
    about_title: "За проекта",
    about_sub: "Кои сме ние и какво правим",
    about_text1: "Aurionyx е независимо студио за Android приложения.",
    about_text2: "Нашата цел е да направим технологиите достъпни за всички.",
    about_dev_title: "Разработчик",
    about_dev_text: "Всички приложения са създадени от Aurionyx.",
    about_contact: "Контакт",
    footer_rights: "Всички права запазени.",
    footer_made: "Създадено с 💚 Aurionyx",
    loading: "Зареждане...",
    no_reviews: "Няма отзиви. Бъдете първи! 💚",
    thanks_feedback: "Благодарим за отзива! 💚",
    error_feedback: "Напишете отзив!"
  }
};

// ===== LANGUAGE MANAGEMENT =====
const langs = ['ru', 'en', 'uk', 'be', 'pl', 'kk', 'bg'];
const langLabels = { ru: 'RU', en: 'EN', uk: 'UA', be: 'BY', pl: 'PL', kk: 'KZ', bg: 'BG' };

let currentLang = localStorage.getItem('aurionyx_lang') || 'ru';

function applyLang() {
  const t = translations[currentLang];
  if (!t) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) el.textContent = t[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.getAttribute('data-i18n-ph');
    if (t[key]) el.placeholder = t[key];
  });
  const langBtn = document.getElementById('langBtn');
  if (langBtn) langBtn.textContent = langLabels[currentLang];
  const langBtnMobile = document.getElementById('langBtnMobile');
  if (langBtnMobile) langBtnMobile.textContent = langLabels[currentLang];
}

function toggleLang() {
  const idx = langs.indexOf(currentLang);
  currentLang = langs[(idx + 1) % langs.length];
  localStorage.setItem('aurionyx_lang', currentLang);
  applyLang();
}

// ===== THEME MANAGEMENT =====
const themes = ['light', 'dark', 'amoled'];
const themeIcons = { light: '🌙', dark: '☀️', amoled: '🌑' };

function applyTheme() {
  const saved = localStorage.getItem('aurionyx_theme') || 'light';
  document.body.setAttribute('data-theme', saved);
  const btn = document.getElementById('themeBtn');
  if (btn) btn.textContent = themeIcons[saved];
  const btnM = document.getElementById('themeBtnMobile');
  if (btnM) btnM.textContent = themeIcons[saved];
}

function cycleTheme() {
  const current = document.body.getAttribute('data-theme') || 'light';
  const idx = themes.indexOf(current);
  const next = themes[(idx + 1) % themes.length];
  document.body.setAttribute('data-theme', next);
  localStorage.setItem('aurionyx_theme', next);
  const btn = document.getElementById('themeBtn');
  if (btn) btn.textContent = themeIcons[next];
  const btnM = document.getElementById('themeBtnMobile');
  if (btnM) btnM.textContent = themeIcons[next];
}

// ===== MOBILE MENU =====
function toggleMobileMenu() {
  const menu = document.getElementById('mobileMenu');
  if (menu) menu.classList.toggle('open');
}

// ===== INIT =====
document.addEventListener('DOMContentLoaded', () => {
  applyTheme();
  applyLang();
});
